# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(937, 740)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Surname_t = QtWidgets.QTextBrowser(self.centralwidget)
        self.Surname_t.setGeometry(QtCore.QRect(70, 80, 191, 31))
        self.Surname_t.setObjectName("Surname_t")
        self.Sur_ok = QtWidgets.QPushButton(self.centralwidget)
        self.Sur_ok.setGeometry(QtCore.QRect(260, 80, 61, 31))
        self.Sur_ok.setObjectName("Sur_ok")
        self.Name_t = QtWidgets.QTextBrowser(self.centralwidget)
        self.Name_t.setGeometry(QtCore.QRect(340, 80, 191, 31))
        self.Name_t.setObjectName("Name_t")
        self.Name_ok = QtWidgets.QPushButton(self.centralwidget)
        self.Name_ok.setGeometry(QtCore.QRect(530, 80, 61, 31))
        self.Name_ok.setObjectName("Name_ok")
        self.Patron_t = QtWidgets.QTextBrowser(self.centralwidget)
        self.Patron_t.setGeometry(QtCore.QRect(630, 80, 191, 31))
        self.Patron_t.setObjectName("Patron_t")
        self.Patron_ok = QtWidgets.QPushButton(self.centralwidget)
        self.Patron_ok.setGeometry(QtCore.QRect(820, 80, 61, 31))
        self.Patron_ok.setObjectName("Patron_ok")
        self.Street_t = QtWidgets.QTextBrowser(self.centralwidget)
        self.Street_t.setGeometry(QtCore.QRect(70, 160, 191, 31))
        self.Street_t.setObjectName("Street_t")
        self.Street_ok = QtWidgets.QPushButton(self.centralwidget)
        self.Street_ok.setGeometry(QtCore.QRect(260, 160, 61, 31))
        self.Street_ok.setObjectName("Street_ok")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(340, 160, 111, 31))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(690, 160, 191, 31))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(470, 160, 81, 31))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(580, 160, 51, 31))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.Surname_l = QtWidgets.QLabel(self.centralwidget)
        self.Surname_l.setGeometry(QtCore.QRect(70, 60, 47, 13))
        self.Surname_l.setObjectName("Surname_l")
        self.Name_l = QtWidgets.QLabel(self.centralwidget)
        self.Name_l.setGeometry(QtCore.QRect(340, 60, 47, 13))
        self.Name_l.setObjectName("Name_l")
        self.Patron_l = QtWidgets.QLabel(self.centralwidget)
        self.Patron_l.setGeometry(QtCore.QRect(630, 60, 47, 13))
        self.Patron_l.setObjectName("Patron_l")
        self.Street_l = QtWidgets.QLabel(self.centralwidget)
        self.Street_l.setGeometry(QtCore.QRect(70, 140, 47, 13))
        self.Street_l.setObjectName("Street_l")
        self.Table = QtWidgets.QTableWidget(self.centralwidget)
        self.Table.setGeometry(QtCore.QRect(70, 260, 811, 411))
        self.Table.setRowCount(15)
        self.Table.setColumnCount(18)
        self.Table.setObjectName("Table")
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(8, item)
        self.Bild_l = QtWidgets.QLabel(self.centralwidget)
        self.Bild_l.setGeometry(QtCore.QRect(340, 140, 47, 13))
        self.Bild_l.setObjectName("Bild_l")
        self.Block_l = QtWidgets.QLabel(self.centralwidget)
        self.Block_l.setGeometry(QtCore.QRect(470, 140, 47, 13))
        self.Block_l.setObjectName("Block_l")
        self.Appr_l = QtWidgets.QLabel(self.centralwidget)
        self.Appr_l.setGeometry(QtCore.QRect(580, 140, 47, 13))
        self.Appr_l.setObjectName("Appr_l")
        self.Number_l = QtWidgets.QLabel(self.centralwidget)
        self.Number_l.setGeometry(QtCore.QRect(690, 140, 47, 13))
        self.Number_l.setObjectName("Number_l")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Sur_ok.setText(_translate("MainWindow", "OK"))
        self.Name_ok.setText(_translate("MainWindow", "OK"))
        self.Patron_ok.setText(_translate("MainWindow", "OK"))
        self.Street_ok.setText(_translate("MainWindow", "OK"))
        self.Surname_l.setText(_translate("MainWindow", "Surname"))
        self.Name_l.setText(_translate("MainWindow", "Name"))
        self.Patron_l.setText(_translate("MainWindow", "Patron"))
        self.Street_l.setText(_translate("MainWindow", "Street"))
        item = self.Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Surname"))
        item = self.Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Patron"))
        item = self.Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Street"))
        item = self.Table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Bild"))
        item = self.Table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Block"))
        item = self.Table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Appr"))
        item = self.Table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Numper"))
        self.Bild_l.setText(_translate("MainWindow", "Bild"))
        self.Block_l.setText(_translate("MainWindow", "Block"))
        self.Appr_l.setText(_translate("MainWindow", "Appr"))
        self.Number_l.setText(_translate("MainWindow", "Number"))

